name: CD Pipeline

on:
  push:
    branches:
      - main  # Runs when code is merged into `main`

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Pulls the latest code

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 13.48.56.51 >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          echo "Deploying to server..."
          ssh -i ~/.ssh/id_rsa ec2-user@13.48.56.51 << 'EOF'
          set -e  # Exit on error
            cd /usr/share/nginx/html/fastapi-book-project
            git config --global --add safe.directory /usr/share/nginx/html/fastapi-book-project
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart fastapi
            sudo systemctl restart nginx
            echo "Deployment complete!"
          EOF
